version: 0.2
phases:
  build:
    commands:
      - echo Entering build phase...
      - sudo npm install -g lerna
      - sudo apt install yarn
      - yarn install
      - lerna bootstrap
      - yarn transpile
      - yarn storybook 
