version: 0.2
phases:
  build:
    commands:
      - echo Entering build phase...
      - npm install -g lerna
      - lerna boostrap
      - yarn storybook
      - yarn transpile
      - yarn storybook 
